#!/bin/sh

# Ensure the correct command is found:
export PATH="/opt/code_saturne/bin":$PATH

# Insert default command
cs_cmd=""
if test $# = 1; then
  if test -f $1; then
    cs_cmd=gui
  fi
elif test $# = 0; then
  cs_cmd=gui
fi

# Run command
\code_saturne $cs_cmd "$@"
